sonar.organization=benburg-git
sonar.projectKey=Benburg-git_SecureFlow-VulnerableCodebase
sonar.projectName=SecureFlow
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/venv/**,**/.venv/**,**/__pycache__/**,**/node_modules/**