sonar.organization=YOUR_ORGANIZATION_KEY
sonar.projectKey=YOUR_PROJECT_KEY
sonar.projectName=SecureFlow
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/venv/**,**/.venv/**,**/__pycache__/**,**/node_modules/**