apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: secureflow

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "frontend"
        vault.hashicorp.com/agent-inject-secret-config: "secureflow/data/frontend"

        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secureflow/data/frontend" -}}
          export AUTH_SERVICE_URL="{{ .Data.data.AUTH_SERVICE_URL }}"
          export TRANSACTION_SERVICE_URL="{{ .Data.data.TRANSACTION_SERVICE_URL }}"
          export SESSION_SECRET="{{ .Data.data.SESSION_SECRET }}"
          {{- end }}

    spec:
      serviceAccountName: frontend-sa

      containers:
        - name: frontend
          image: secureflow/frontend:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 5000

          command:
            - /bin/sh
            - -c

          args:
            - |
              . /vault/secrets/config
              exec python app.py

          envFrom:
            - configMapRef:
                name: secureflow-config

          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL

---

apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: secureflow

spec:
  type: NodePort

  selector:
    app: frontend

  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080