apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisallowPrivileged

metadata:
  name: secureflow-disallow-privileged

spec:
  enforcementAction: dryrun

  match:
    kinds:
      - apiGroups:
          - ""
          - apps

        kinds:
          - Pod
          - Deployment

    namespaces:
      - secureflow